[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
duct = "0.13.7"
chrono = "0.4.37"
bunt = "0.2.8"
